In [1]:
######################################
## running kernel is axolotl_omics_py3.12 
## mainly processing anndata object for Seurat object
######################################

In [2]:
import sys
print(sys.executable)
print(sys.version)
print(sys.version_info)

/groups/tanaka/People/current/jiwang/local/anaconda3/envs/axoBrain_omcs_py3.12/bin/python
3.12.13 | packaged by conda-forge | (main, Mar  5 2026, 16:50:00) [GCC 14.3.0]
sys.version_info(major=3, minor=12, micro=13, releaselevel='final', serial=0)

In [3]:
import os
import warnings

#import moscot as mt
#import moscot.plotting as mpl
#from moscot.problems.time import TemporalProblem

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

warnings.simplefilter("ignore", UserWarning)
warnings.simplefilter("ignore", FutureWarning)

In [4]:
#from scanpy import read

In [5]:
import scanpy as sc

plt.rcParams["legend.scatterpoints"] = 1
sc.set_figure_params(scanpy=True, dpi=80, dpi_save=200)

In [6]:
#mt.__version__, sc.__version__

In [7]:
import h5py

In [8]:
inputDir = "/groups/tanaka/Collaborations/axolotlBrain_Omics/data_shared_Mateja/"
outDir = "/groups/tanaka/Collaborations/axolotlBrain_Omics/Rdata"

In [9]:
#file_name = "scRNAseq_RA_d2_d2.5_d3_d4_d5_TFsubclustersAnnot_forOTtest_v2.h5ad"
#file_name = "Retina.h5ad"
#file_name = "Hindbrain.h5ad"
#brain_section = 'Hindbrain'
file_name = "Midbrain.h5ad"
brain_section = 'Midbrain'
#file_name = "scRNAseq_RA_d2_d2.5_d3_d4_d5_TFsubclustersAnnot_forOTtest_downsampled2000_tfsPCs30.h5ad"
file_path = os.path.join(inputDir, file_name)
file_path

'/groups/tanaka/Collaborations/axolotlBrain_Omics/data_shared_Mateja/Midbrain.h5ad'

In [10]:
adata = sc.read(file_path, cache=True)

In [11]:
adata

AnnData object with n_obs × n_vars = 19357 × 29812
    obs: 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'n_genes', 'n_counts', 'doublet_score', 'predicted_doublet', 'batch', 'library', 'dissection', 'subdissection', 'technology', 'batch_density', 'merged_cluster', 'cluster'
    var: 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection'
    uns: 'batch_colors', 'batch_density_params', 'dissection_colors', 'hvg', 'leiden', 'library_colors', 'log1p', 'merged_cluster_colors', 'neighbors', 'pca', 'technology_colors', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'

In [12]:
adata.obsm['X_pca']

array([[-0.19270246, -0.5795902 ,  2.1401238 , ...,  1.1959293 ,
        -0.14941844,  1.0138276 ],
       [-0.6490788 ,  0.14843911,  1.497805  , ..., -1.4076325 ,
         1.3734168 ,  0.0399897 ],
       [-0.65880466,  1.564848  ,  2.946412  , ..., -0.34288958,
        -0.37753597,  1.9682797 ],
       ...,
       [-8.823501  , -4.4481463 , -1.7811459 , ..., -1.3888607 ,
        -0.10017715,  0.922146  ],
       [-1.8800933 , -1.2573555 , -1.3831148 , ..., -0.68612856,
         0.9971202 , -0.52778524],
       [-1.1540952 , -1.0710526 , -2.2540476 , ..., -0.48767555,
         0.9356314 ,  0.31632894]], shape=(19357, 50), dtype=float32)

In [13]:
### save count matrix 
counts = adata.layers["counts"]
df = pd.DataFrame(
    counts.toarray() if hasattr(counts, "toarray") else counts,
    index=adata.obs_names,
    columns=adata.var_names
)

In [14]:
brain_section + "_adata_layer_counts.csv"

'Midbrain_adata_layer_counts.csv'

In [15]:
df.to_csv(os.path.join(outDir,  brain_section + "_adata_layer_counts.csv"))

In [16]:
### save metadata
metadata = adata.obs
metadata

,n_genes_by_counts,log1p_n_genes_by_counts,total_counts,log1p_total_counts,pct_counts_in_top_50_genes,pct_counts_in_top_100_genes,pct_counts_in_top_200_genes,pct_counts_in_top_500_genes,total_counts_mito,log1p_total_counts_mito,...,doublet_score,predicted_doublet,batch,library,dissection,subdissection,technology,batch_density,merged_cluster,cluster
7_GGGATGAAGAACGTGC,4079,8.313852,8854.0,9.088737,9.103230,14.468037,22.351480,38.344251,32.0,3.496508,...,0.062079,False,Lust_V3,Lust_V3_M1,Pallium,Medial_Pallium,10X_V3.1,0.702774,3,3
8_GCCCGAAGTTTCACAG,2557,7.846981,4546.0,8.422223,11.152662,17.267928,26.792785,45.380554,26.0,3.295837,...,0.057406,False,Lust_V3,Lust_V3_M2,Pallium,Medial_Pallium,10X_V3.1,0.123853,3,3
8_GCCGTGAGTTAAGTCC,2692,7.898411,4458.0,8.402679,9.869897,15.769403,24.719605,42.081651,17.0,2.890372,...,0.045928,False,Lust_V3,Lust_V3_M2,Pallium,Medial_Pallium,10X_V3.1,0.692360,7,7
9_AGGGCCTAGATCGCCC,5109,8.538955,15059.0,9.619798,10.113553,15.578724,23.786440,39.517896,15.0,2.772589,...,0.020113,False,Lust_V3,Lust_V3_L1,Pallium,Lateral_Pallium,10X_V3.1,0.680402,11,11
9_ATCCTATAGTAATACG,5006,8.518592,16082.0,9.685518,11.229947,17.746549,26.395971,42.208681,14.0,2.708050,...,0.035665,False,Lust_V3,Lust_V3_L1,Pallium,Lateral_Pallium,10X_V3.1,0.960758,68,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23_TGTAACTCACAAGCCT,2075,7.638198,3366.0,8.121778,13.576946,20.617944,30.808081,50.356506,22.0,3.135494,...,0.040301,False,10X_Multiome_New,10X_Multiome_New_Midbrain,Midbrain,Midbrain,10X_Multiome,0.056929,210,212
23_TGTGTGAGTGTTTGAG,1147,7.045777,1564.0,7.355641,15.025575,23.465473,36.253197,58.631714,14.0,2.708050,...,0.043089,False,10X_Multiome_New,10X_Multiome_New_Midbrain,Midbrain,Midbrain,10X_Multiome,0.080203,210,212
23_TTACACCGTCAATAGT,1234,7.118826,1558.0,7.351800,12.836970,20.218228,33.055199,52.888318,5.0,1.791759,...,0.041667,False,10X_Multiome_New,10X_Multiome_New_Midbrain,Midbrain,Midbrain,10X_Multiome,0.082563,210,212
23_TTCGTTAGTTTGTTGC,3733,8.225235,8001.0,8.987447,12.360955,18.310211,26.684164,43.007124,9.0,2.302585,...,0.047733,False,10X_Multiome_New,10X_Multiome_New_Midbrain,Midbrain,Midbrain,10X_Multiome,0.056222,210,212
25_CGTAACTAGTTCCTGC,4048,8.306225,9745.0,9.184612,12.929708,19.168805,27.860441,44.227809,22.0,3.135494,...,0.092697,False,10X_Multiome_New,10X_Multiome_New_HS2,Hindbrain+Striatum,Hindbrain+Striatum,10X_Multiome,0.047598,210,212

In [17]:
adata.obs.to_csv(os.path.join(outDir, brain_section + "_adata_metacell.csv"))

In [18]:
adata

AnnData object with n_obs × n_vars = 19357 × 29812
    obs: 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'n_genes', 'n_counts', 'doublet_score', 'predicted_doublet', 'batch', 'library', 'dissection', 'subdissection', 'technology', 'batch_density', 'merged_cluster', 'cluster'
    var: 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection'
    uns: 'batch_colors', 'batch_density_params', 'dissection_colors', 'hvg', 'leiden', 'library_colors', 'log1p', 'merged_cluster_colors', 'neighbors', 'pca', 'technology_colors', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'

In [19]:
adata.obsm["X_umap"]

array([[ 7.8974233,  4.845993 ],
       [ 8.92478  ,  3.97788  ],
       [ 8.548995 ,  6.403632 ],
       ...,
       [12.686441 , -2.5418534],
       [13.297656 , -2.915505 ],
       [13.321946 , -3.0168693]], shape=(19357, 2), dtype=float32)

In [20]:
umap_df = pd.DataFrame(
    adata.obsm["X_umap"],
    index=adata.obs_names,
    columns=["UMAP1", "UMAP2"]
)
umap_df.to_csv(os.path.join(outDir, brain_section + "_adata_rd_umap.csv"))

In [21]:
adata.obsm["X_pca_harmony"]
pca_harmony_df = pd.DataFrame(
    adata.obsm["X_pca_harmony"],
    index=adata.obs_names
)
pca_harmony_df.to_csv(os.path.join(outDir, brain_section + "_adata_rd_pca_harmony.csv"))

In [22]:
pca_harmony_df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
7_GGGATGAAGAACGTGC,-1.350171,-0.419758,2.094797,-0.165361,4.947403,0.448631,-0.574696,-2.324130,-0.487433,-0.371331,...,0.774043,0.216376,0.079862,-0.718148,0.120254,-0.300687,0.368469,0.872354,-0.064933,0.295352
8_GCCCGAAGTTTCACAG,-0.747286,0.395694,2.127431,0.150355,2.639662,-0.930183,-0.453975,-1.705748,-0.823400,-0.385651,...,0.173853,-0.365966,0.941496,-1.159805,0.330502,0.566208,1.419466,-1.168488,1.017248,-0.116747
8_GCCGTGAGTTAAGTCC,-0.940102,0.715688,3.226946,-2.207713,1.907959,-0.362303,1.342397,-1.288854,1.037513,-0.999217,...,0.941314,-1.020110,0.822881,-0.633455,0.506531,0.185672,-0.415590,-0.341587,-0.583784,1.074277
9_AGGGCCTAGATCGCCC,-1.063165,-1.513347,2.372516,1.359057,-0.842475,-0.987528,-1.161547,-2.215783,-1.505523,-0.899684,...,0.524295,-1.031150,-0.313487,-0.021228,0.315032,-0.843310,-1.164800,0.101260,0.064773,1.044314
9_ATCCTATAGTAATACG,-0.835395,0.170685,0.954391,1.113249,0.597587,-1.805846,0.218355,-0.550513,-0.315296,-0.371760,...,0.164020,0.460480,-0.517177,-0.363873,1.314969,0.294583,-1.876622,-0.253589,-0.746221,1.492745
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23_TGTAACTCACAAGCCT,-1.708036,-1.286289,-0.607676,-1.530379,0.043436,-4.983120,-4.097085,2.847541,-2.768990,0.129796,...,1.334697,0.748419,-0.388455,0.660233,0.246066,-0.768267,-0.906102,-0.376525,-1.127670,-0.419260
23_TGTGTGAGTGTTTGAG,-6.602654,-2.928287,-1.470045,-1.347014,-0.692061,-3.005769,-4.242423,0.700967,-1.269087,0.599451,...,0.556253,-0.384350,-0.787528,0.492608,-0.414193,0.386011,-0.250126,-2.284076,-0.068766,0.043879
23_TTACACCGTCAATAGT,-7.219556,-3.331474,-0.918250,-2.440138,-0.769075,-3.690440,-3.023134,1.060926,-2.095285,1.399355,...,0.217897,-0.686281,-0.842512,1.046307,-0.647856,-0.146174,-0.443288,-1.261644,0.037684,0.880135
23_TTCGTTAGTTTGTTGC,-0.392706,-0.158895,-0.499582,-1.480103,-0.425777,-5.402781,-4.672415,1.630722,-2.718088,1.678869,...,0.260176,0.743772,-1.035163,-0.682621,0.486118,-1.719557,0.592633,-0.561446,1.163126,-0.573316
25_CGTAACTAGTTCCTGC,0.333292,0.027408,-1.370516,-2.309831,-0.726167,-5.201781,-3.160322,1.367964,-1.666377,0.900247,...,0.406860,0.322712,-1.470762,0.072047,-0.762172,0.352766,0.640061,-0.362993,1.101637,0.270798

In [23]:
pca_df = pd.DataFrame(
    adata.obsm["X_pca"],
    index=adata.obs_names
)
pca_df.to_csv(os.path.join(outDir, brain_section + "_adata_rd_pca.csv"))